### ISSUE TITLE
Nightly builds stopped running

### ISSUE THREAD

**Issue by Morl99** [dbsystel/postgresql-partman-container#9]
Somehow the cron actions stopped triggering 3 weeks ago. Why?

**Comment by jschirrmacher** [comment]
Might that be a result of some changes in Github actions, that were announced in the deprecation warnings in the previous action runs?
https://github.com/dbsystel/postgresql-partman-container/actions/runs/6307338728

We should maybe update the workflow so that the warnings disappear.

**Comment by Morl99** [comment]
Since the last push to main triggered a build, it has to be specific to scheduled actions. Maybe GitHub disables actions for Repos that have been inactive for a longer period of time? Let's see if it will work from today on.

Fixing the deprecations sure is a good idea anyways.

**Comment by Morl99** [comment]
These now work again, so I close this issue for the moment.
